name: Actividad02 - DocFX en GitHubPages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Restore dependencies
      run: dotnet restore
      working-directory: Calculator

    - name: Generate API Metadata
      run: docfx metadata
      working-directory: Calculator

    - name: Build DocFX site
      run: docfx build
      working-directory: Calculator

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Calculator/_site
        publish_branch: gh-pages
        user_name: 'GitHub Actions'
        user_email: 'github-actions@users.noreply.github.com'
        keep_files: true